name: 161
displayName: Birth in France by department in 2016
fullyQualifiedName: sample_superset.161
description: ""
chartType: Other
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20161%7D
owners: []
tags: []
service:
  id: 030e1103-e57e-41d9-aede-8956f7743365
  type: dashboardService
  name: sample_superset
  fullyQualifiedName: sample_superset
  displayName: sample_superset
  deleted: false
serviceType: Superset
domains: []
dataProducts: []
dashboards:
  - id: c9e34a3f-16f3-4300-8b06-7edca8518f65
    type: dashboard
    name: 34
    fullyQualifiedName: sample_superset.34
    description: ""
    displayName: Unicode Test
    deleted: false
entityStatus: Unprocessed
