name: 211
displayName: Sales Predictions Accuracy
fullyQualifiedName: sample_superset.211
description: ""
chartType: Line
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20180%7D
owners: []
tags: []
service:
  id: 030e1103-e57e-41d9-aede-8956f7743365
  type: dashboardService
  name: sample_superset
  fullyQualifiedName: sample_superset
  displayName: sample_superset
  deleted: false
serviceType: Superset
domains: []
dataProducts: []
dashboards:
  - id: fac262ab-99d8-43f3-8cde-3800197b7356
    type: dashboard
    name: forecast_sales_performance
    fullyQualifiedName: sample_superset.forecast_sales_performance
    description: ""
    displayName: ETA Predictions Performance
    deleted: false
entityStatus: Unprocessed
