name: chart_4
displayName: Chart 4
fullyQualifiedName: sample_looker.chart_4
description: This is a sample Chart for Looker
chartType: Histogram
sourceUrl: http://localhost:8088/looker/explore/?form_data=%7B%22slice_id%22%3A%20117%7D
owners: []
tags: []
service:
  id: 78b5454b-4f82-447e-8d7f-4081e5cdce8d
  type: dashboardService
  name: sample_looker
  fullyQualifiedName: sample_looker
  displayName: sample_looker
  deleted: false
serviceType: Looker
domains: []
dataProducts: []
dashboards:
  - id: cd1feb73-439f-4cf5-b8b8-97eb4ffdc108
    type: dashboard
    name: orders
    fullyQualifiedName: sample_looker.orders
    description: This is a sample Dashboard for Looker
    displayName: Orders Dashboard
    deleted: false
entityStatus: Unprocessed
