name: 210
displayName: ETA Predictions Accuracy
fullyQualifiedName: sample_superset.210
description: ""
chartType: Line
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20180%7D
owners: []
tags: []
service:
  id: 030e1103-e57e-41d9-aede-8956f7743365
  type: dashboardService
  name: sample_superset
  fullyQualifiedName: sample_superset
  displayName: sample_superset
  deleted: false
serviceType: Superset
domains: []
dataProducts: []
dashboards:
  - id: 2cb31814-5124-4b8d-b397-789d236b6120
    type: dashboard
    name: eta_predictions_performance
    fullyQualifiedName: sample_superset.eta_predictions_performance
    description: ""
    displayName: ETA Predictions Performance
    deleted: false
entityStatus: Unprocessed
