name: 166
displayName: '% Rural'
fullyQualifiedName: sample_superset.166
description: ""
chartType: Other
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20166%7D
owners: []
tags: []
service:
  id: 030e1103-e57e-41d9-aede-8956f7743365
  type: dashboardService
  name: sample_superset
  fullyQualifiedName: sample_superset
  displayName: sample_superset
  deleted: false
serviceType: Superset
domains: []
dataProducts: []
dashboards:
  - id: 30f0a084-a386-4b67-84e8-27717c3e828f
    type: dashboard
    name: 10
    fullyQualifiedName: sample_superset.10
    description: ""
    displayName: deck.gl Demo
    deleted: false
  - id: 4b7ac31a-f415-40e2-a145-3c584af62071
    type: dashboard
    name: 31
    fullyQualifiedName: sample_superset.31
    description: ""
    displayName: Sales Dashboard
    deleted: false
entityStatus: Unprocessed
