name: column_values_to_match_regex
fullyQualifiedName: sample_data.ecommerce_db.shopify.dim_address.last_name.column_values_to_match_regex
description: test value of a column match regex
testDefinition:
  id: 20495f70-318a-425e-ba68-532530eb0f5d
  type: testDefinition
  name: columnValuesToMatchRegex
  fullyQualifiedName: columnValuesToMatchRegex
  description: 'This schema defines the test ColumnValuesToMatchRegex. Test the values
    in a column to match a given regular expression. '
  displayName: Column Values To Match Regex Pattern
  deleted: false
entityLink: <#E::table::sample_data.ecommerce_db.shopify.dim_address::columns::last_name>
entityFQN: sample_data.ecommerce_db.shopify.dim_address.last_name
testSuite:
  id: c36983e3-01b1-4da5-bf78-4e9a0182efff
  type: testSuite
  name: sample_data.ecommerce_db.shopify.dim_address.testSuite
  fullyQualifiedName: sample_data.ecommerce_db.shopify.dim_address.testSuite
  description: This is an executable test suite linked to an entity
  displayName: sample_data.ecommerce_db.shopify.dim_address.testSuite
  deleted: false
testSuites:
  - id: 68219aad-a67d-42d1-8e26-5ef8a4d3386a
    name: myLogicalTestSuite
    fullyQualifiedName: myLogicalTestSuite
    description: This is a logical test suite linked to an entity
    serviceType: TestSuite
    owners: []
    version: 0.1
    updatedAt: 1771488555454
    updatedBy: admin
    deleted: false
    basic: false
    testCaseResultSummary: []
    tags: []
    inherited: true
    reviewers: []
  - id: c36983e3-01b1-4da5-bf78-4e9a0182efff
    name: sample_data.ecommerce_db.shopify.dim_address.testSuite
    fullyQualifiedName: sample_data.ecommerce_db.shopify.dim_address.testSuite
    description: This is an executable test suite linked to an entity
    serviceType: TestSuite
    owners: []
    version: 0.1
    updatedAt: 1771488524784
    updatedBy: admin
    deleted: false
    basic: true
    basicEntityReference:
      id: 6c0cce20-3060-4d8a-8bfb-35b68cbf5379
      type: table
      name: dim_address
      fullyQualifiedName: sample_data.ecommerce_db.shopify.dim_address
    testCaseResultSummary: []
    domains: []
    tags: []
    inherited: true
    reviewers: []
parameterValues:
  - name: regex
    value: Doe.*
testCaseResult:
  id: 19c8ca69-db04-4dfb-86e7-6acbe502f829
  testCaseFQN: sample_data.ecommerce_db.shopify.dim_address.last_name.column_values_to_match_regex
  timestamp: 1771488541316
  testCaseStatus: Success
  result: Found 99 value(s) matching regex pattern vs 99 value(s) in the column.
  testResultValue:
    - name: likeCount
      value: 65
  dimensionResults: []
testCaseStatus: Success
owners: []
createdBy: admin
incrementalChangeDescription:
  fieldsAdded:
    - name: testCaseStatus
      newValue: Success
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary: {}
computePassedFailedRowCount: false
domains: []
useDynamicAssertion: false
tags:
  - tagFQN: PII.Sensitive
    name: Sensitive
    description: "PII which if lost, compromised, or disclosed without authorization,\
      \ could result in substantial harm, embarrassment, inconvenience, or unfairness\
      \ to an individual."
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1771488495773
dimensionColumns: []
entityStatus: Unprocessed
reviewers: []
